resource.AddFile( "sound/advert.wav" )
resource.AddFile( "sound/doormod_disrupted.wav" )
resource.AddFile( "sound/doormod_loop.wav" )
resource.AddFile( "sound/weldspark.wav" )

resource.AddFile( "materials/vgui/gradient-bl.vmt" )
resource.AddFile( "materials/vgui/gradient-bl.vtf" )
resource.AddFile( "materials/vgui/gradient-br.vmt" )
resource.AddFile( "materials/vgui/gradient-br.vtf" )
resource.AddFile( "materials/vgui/gradient-l.vmt" )

resource.AddFile( "materials/hudicons/c4.vmt" )
resource.AddFile( "materials/hudicons/c4.vtf" )
resource.AddFile( "materials/hudicons/fnade.vmt" )
resource.AddFile( "materials/hudicons/fnade.vtf" )
resource.AddFile( "materials/hudicons/health.vmt" )
resource.AddFile( "materials/hudicons/health.vtf" )
resource.AddFile( "materials/hudicons/health2.vmt" )
resource.AddFile( "materials/hudicons/health2.vtf" )
resource.AddFile( "materials/hudicons/henade.vmt" )
resource.AddFile( "materials/hudicons/henade.vtf" )
resource.AddFile( "materials/hudicons/shield.vmt" )
resource.AddFile( "materials/hudicons/shield.vtf" )
resource.AddFile( "materials/hudicons/snade.vmt" )
resource.AddFile( "materials/hudicons/snade.vtf" )

resource.AddFile( "materials/toolicons/propspawn.vmt" )
resource.AddFile( "materials/toolicons/propspawn.vtf" )
resource.AddFile( "materials/toolicons/remover.vmt" )
resource.AddFile( "materials/toolicons/remover.vtf" )
resource.AddFile( "materials/toolicons/repair.vmt" )
resource.AddFile( "materials/toolicons/repair.vtf" )
resource.AddFile( "materials/toolicons/spawnpoint.vmt" )
resource.AddFile( "materials/toolicons/spawnpoint.vtf" )
resource.AddFile( "materials/toolicons/ammocrate_closed.vmt" )
resource.AddFile( "materials/toolicons/ammocrate_closed.vtf" )
resource.AddFile( "materials/toolicons/ammocrate_open.vmt" )
resource.AddFile( "materials/toolicons/ammocrate_open.vtf" )

resource.AddFile( "materials/blood/blood_spray.vmt" )
resource.AddFile( "materials/blood/blood_spray.vtf" )
resource.AddFile( "materials/blood/dying.vmt" )
resource.AddFile( "materials/blood/dying.vtf" )
resource.AddFile( "materials/blood/bsplatv1.vmt" )
resource.AddFile( "materials/blood/bsplatv1.vtf" )

resource.AddFile( "materials/scope/scope_normal.vmt" )
resource.AddFile( "materials/scope/scope_normal.vtf" )

resource.AddFile( "materials/scope/acog_reticle.vtf" )
resource.AddFile( "materials/scope/acog_reticle.vmt" )

resource.AddFile( "materials/scope/augret.vtf" )
resource.AddFile( "materials/scope/augret.vmt" )

resource.AddFile( "materials/doormod_blocked.vmt" )
resource.AddFile( "materials/doormod_unblocked.vmt" )

resource.AddFile( "materials/tool_radialbg.vmt" )
resource.AddFile( "materials/tool_radialbg.vtf" )

resource.AddFile( "materials/tool_radialselect.vmt" )
resource.AddFile( "materials/tool_radialselect.vtf" )

resource.AddFile( "materials/vignette.vmt" )
resource.AddFile( "materials/vignette.vtf" )

-- Explosion / Hit effects
resource.AddFile( "materials/refract_ring.vmt" )
resource.AddFile( "materials/refract_ring.vtf" )

resource.AddFile( "materials/effects/dust.vmt" )
resource.AddFile( "materials/effects/dust2.vmt" )
resource.AddFile( "materials/effects/dust.vtf" )
resource.AddFile( "materials/effects/dust2.vtf" )

-- Toolgun Shoot
resource.AddFile( "sound/weapons/alyx_gun/alyx_gun_fire3.wav" )
resource.AddFile( "sound/weapons/alyx_gun/alyx_gun_fire4.wav" )

-- Ammo Crate
resource.AddFile( "models/Items/ammocrate_smg2.mdl" )
resource.AddFile( "materials/models/Items/ammocrate_smg1.vmt" )
resource.AddFile( "materials/models/Items/ammocrate_smg1.vtf" )
resource.AddFile( "materials/models/Items/ammocrate_smg2.vmt" )
resource.AddFile( "materials/models/Items/ammocrate_smg2.vtf" )

resource.AddFile( "models/weapons/v_slam.mdl" )
resource.AddFile( "models/weapons/w_slam.mdl" )

resource.AddFile( "materials/toolicons/BG.vtf")
resource.AddFile( "materials/toolicons/BG.vmt")
resource.AddFile( "materials/screen/weaponcrate.vtf")
resource.AddFile( "materials/screen/weaponcrate.vmt")
resource.AddFile( "materials/screen/propspawn.vtf")
resource.AddFile( "materials/screen/propspawn.vmt")
resource.AddFile( "materials/screen/repair.vtf")
resource.AddFile( "materials/screen/repair.vmt")
resource.AddFile( "materials/screen/remover.vtf")
resource.AddFile( "materials/screen/remover.vmt")
resource.AddFile( "materials/screen/mobilesp.vtf")
resource.AddFile( "materials/screen/mobilesp.vmt")

resource.AddFile( "sound/hit1.wav")
resource.AddFile( "sound/hit2.wav")
resource.AddFile( "sound/hit3.wav")
resource.AddFile( "sound/weapons/alyx_gun/alyx_gun_fire3.wav")
resource.AddFile( "sound/weapons/alyx_gun/alyx_gun_fire4.wav")
resource.AddFile( "sound/weapons/alyx_gun/alyx_gun_fire5.wav")
resource.AddFile( "sound/weapons/alyx_gun/alyx_gun_fire6.wav")

resource.AddFile( "sound/weapons/suppressed_pistol.wav")
resource.AddFile( "sound/weapons/suppressed_ar.wav")
resource.AddFile( "sound/weapons/suppressed_m4.wav")
resource.AddFile( "sound/weapons/suppressed_ak.wav")
resource.AddFile( "sound/weapons/suppressed_p90.wav")
resource.AddFile( "sound/weapons/suppressed_ump.wav")
resource.AddFile( "sound/weapons/suppressed_552.wav")
resource.AddFile( "sound/weapons/suppressed_usp.wav")
resource.AddFile("sound/weapons/flashbang_explode1.wav")
resource.AddFile("sound/weapons/grenade_hit1.wav")

resource.AddFile( "sound/distantsound/ak.mp3")
resource.AddFile( "sound/distantsound/aug.mp3")
resource.AddFile( "sound/distantsound/awp.mp3")
resource.AddFile( "sound/distantsound/deagle.mp3")
resource.AddFile( "sound/distantsound/famas.mp3")
resource.AddFile( "sound/distantsound/fiveseven.mp3")
resource.AddFile( "sound/distantsound/g3sg1.mp3")
resource.AddFile( "sound/distantsound/galil.mp3")
resource.AddFile( "sound/distantsound/glock.mp3")
resource.AddFile( "sound/distantsound/m4.mp3")
resource.AddFile( "sound/distantsound/mac.mp3")
resource.AddFile( "sound/distantsound/mp5.mp3")
resource.AddFile( "sound/distantsound/p90.mp3")
resource.AddFile( "sound/distantsound/p228.mp3")
resource.AddFile( "sound/distantsound/scout.mp3")
resource.AddFile( "sound/distantsound/sg550.mp3")
resource.AddFile( "sound/distantsound/sg552.mp3")
resource.AddFile( "sound/distantsound/shotty.mp3")
resource.AddFile( "sound/distantsound/ump.mp3")
resource.AddFile( "sound/distantsound/pumpshot.mp3")
resource.AddFile( "materials/hitdetection2.vmt")
resource.AddFile( "materials/hitdetection2.vtf")
resource.AddFile( "resource/cs.ttf" ) 

-- GUI materials removed by Garry :D

resource.AddFile( "materials/gui/silkicons/add.vmt" )
resource.AddFile( "materials/gui/silkicons/application_form_magnify.vmt" )
resource.AddFile( "materials/gui/silkicons/application_put.vmt" )
resource.AddFile( "materials/gui/silkicons/application_view_detail.vmt" )
resource.AddFile( "materials/gui/silkicons/application_view_tile.vmt" )
resource.AddFile( "materials/gui/silkicons/arrow_refresh.vmt" )
resource.AddFile( "materials/gui/silkicons/bomb.vmt" )
resource.AddFile( "materials/gui/silkicons/box.vmt" )
resource.AddFile( "materials/gui/silkicons/plugin.vmt" )
resource.AddFile( "materials/gui/silkicons/table_edit.vmt" )
resource.AddFile( "materials/gui/silkicons/user.vmt" )
resource.AddFile( "materials/gui/silkicons/wrench.vmt" )

resource.AddFile( "materials/maps/noicon.vmt" )

-- Scoreboard
resource.AddFile( "materials/gui/silkicons/leader.vmt" )
resource.AddFile( "materials/vgui/stronghold/scoreboard_header.vmt" )

resource.AddFile( "models/uplink/uplink.mdl" )

resource.AddFile( "models/weapons/v_rc_m4a1.mdl" )
resource.AddFile( "models/weapons/v_rc_p90.mdl" )
resource.AddFile( "models/weapons/v_rc_g3sg1.mdl" )
resource.AddFile( "models/weapons/v_rc_galil.mdl" )
resource.AddFile( "models/weapons/v_rc_sg552.mdl" )
resource.AddFile( "models/weapons/v_rc_m249para.mdl" )
resource.AddFile( "models/weapons/v_rc_awp.mdl" )
resource.AddFile( "models/weapons/v_rc_scout.mdl" )
resource.AddFile( "models/weapons/v_rc_aug.mdl" )

resource.AddFile( "models/weapons/rail.mdl")
resource.AddFile( "models/weapons/rds.mdl")
resource.AddFile( "models/weapons/m145.mdl")
resource.AddFile( "models/weapons/akmount.mdl")
resource.AddFile( "models/weapons/suppressor.mdl")
resource.AddFile( "models/weapons/scope.mdl")
resource.AddFile( "models/weapons/mrds.mdl")
resource.AddFile( "models/weapons/augrail.mdl")
resource.AddFile( "models/weapons/irons.mdl")
resource.AddFile( "models/weapons/irons_f.mdl")

resource.AddFile( "materials/models/uplink/uplink.vmt" )
resource.AddFile( "materials/models/uplink/uplink.vtf" )
resource.AddFile( "materials/models/rail/rail.vmt" )
resource.AddFile( "materials/models/rail/rail.vtf" )
resource.AddFile( "materials/models/rds/rds.vmt" )
resource.AddFile( "materials/models/rds/rds.vtf" )
resource.AddFile( "materials/models/rds/rds_bmp.vtf" )
resource.AddFile( "materials/models/m145/m145.vmt" )
resource.AddFile( "materials/models/m145/m145.vtf" )
resource.AddFile( "materials/models/m145/m145_bmp.vtf" )
resource.AddFile( "materials/models/suppressor/suppressor.vmt" )
resource.AddFile( "materials/models/suppressor/suppressor.vtf" )
resource.AddFile( "materials/models/suppressor/suppressor_bmp.vtf" )
resource.AddFile( "materials/models/scope/scope.vtf" )
resource.AddFile( "materials/models/scope/scope.vmt" )
resource.AddFile( "materials/models/scope/scope_bmp.vtf" )
resource.AddFile( "materials/scope/m145_reticle.vtf" )
resource.AddFile( "materials/scope/m145_reticle.vmt" )
resource.AddFile( "materials/models/mrds/mrds.vtf" )
resource.AddFile( "materials/models/mrds/mrds_bmp.vtf" )
resource.AddFile( "materials/models/mrds/mrds.vmt" )
resource.AddFile( "materials/models/mrds/augrail.vtf" )
resource.AddFile( "materials/models/mrds/augrail_bmp.vtf" )
resource.AddFile( "materials/models/mrds/augrail.vmt" )
resource.AddFile( "materials/models/akmount/akmount.vtf" )
resource.AddFile( "materials/models/akmount/akmount_bmp.vtf" )
resource.AddFile( "materials/models/akmount/akmount.vmt" )

resource.AddFile( "materials/models/augrail/augrail.vmt" )
resource.AddFile( "materials/models/augrail/augrail.vtf" )
resource.AddFile( "materials/models/augrail/augrail_bmp.vtf" )
resource.AddFile( "materials/models/irons/irons.vtf" )
resource.AddFile( "materials/models/irons/irons_bmp.vtf" )
resource.AddFile( "materials/models/irons/irons.vmt" )




